### PR TITLE
update to 1.0.2

### PR DESCRIPTION
**Pull request by glitchcrab**
This PR updates cert-manager to the latest stable release. As part of this there are some bigger changes in the chart:

- the crds have been split into their own configmaps. this is because when combined they exceed the maximum allowed length for a configmap.
- because of the above, each configmap is mounted individually in the pod using subPaths.
- the crd cleanup subchart has been dropped in favour of the `hook-delete-policy": "before-hook-creation` annotation on CRD creation resources.
- the `giantswarm-clusterissuer` is only created on initial install.
- error logs are surfaced better when using `kubectl` - previously `stderr` was lost, making it hard to troubleshoot failures.

### testing

- [x] optional app fresh install 
- [x] optional app upgrade from 0.2.4
- [x] preinstalled app fresh install (cluster override)
- [x] preinstalled app upgrade from 0.2.4

### CODE REVIEW

**Comment by glitchcrab** [comment]
I ran into some issues with upgrades doing funky stuff (release upgrade failed and the crd install hook kept repeating. This requires some more digging.

**Comment by ced0ps** [comment]
What's the reasoning to have the crds in folder `files` instead of `crd`? @glitchcrab

**Comment by glitchcrab** [comment]
> What's the reasoning to have the crds in folder `files` instead of `crd`? @glitchcrab

because the CRDs need to be templated and you can't do that with the `crds` folder.

**Comment by ced0ps** [comment]
> > What's the reasoning to have the crds in folder `files` instead of `crd`? @glitchcrab
> 
> because the CRDs need to be templated and you can't do that with the `crds` folder.

got it. I'd consider reapplying the crd-prefix to make the files more identifiable.

**Comment by ced0ps** [comment]
> > > What's the reasoning to have the crds in folder `files` instead of `crd`? @glitchcrab
> > 
> > 
> > because the CRDs need to be templated and you can't do that with the `crds` folder.
> 
> got it. I'd consider reapplying the crd-prefix to make the files more identifiable. But def not critical

ignore. found the template folder.

**Review by ced0ps — APPROVED** [review]
LGTM with a BOULDER of salt. This stuff is complex

**Pull request merged**
