### PR TITLE
Cainjector toleration v2

### PR DESCRIPTION
**Pull request by ubergesundheit**
This PR removes the CA injector toleration for control plane nodes for v2.x.x

### Checklist

- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by Gacko** [comment]
Is everything fine with this PR? It looks like you are also reverting the whole alignment or at least like it was based on the new version.

**Review by Gacko — CHANGES_REQUESTED** [review]
Is everything fine with this PR? It looks like you are also reverting the whole alignment or at least like it was based on the new version.

**Comment by ubergesundheit** [comment]
yes this is meant for v2. I reverted the alignment stuff because v2 shouldn't be aligned

**Comment by Gacko** [comment]
Ah, I get you! I just reset and force-pushed the `release-*` branch in the past before applying new changes because the whole "create a release-* branch right before releasing a new version" is not working as intended.

**Review by Gacko — APPROVED** [review]
Discussed in Meet, fine so far.

**Review by ced0ps — APPROVED** [review]
LGTM

**Pull request merged**
