### PR TITLE
Docs: Replace `main` by `master`.

### PR DESCRIPTION
**Pull request by mleisa**
This PR:

- fixes a link in the readme 

#### Optional app

- [ ] fresh install
- [ ] upgrade from previous version

#### Pre-installed app

- [ ] fresh install during cluster creation
- [ ] upgrade from previous version in a pre-existing cluster

#### Other testing

- [ ] check reconciliation of existing resources after upgrading

### Checklist

- [ ] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Review by ubergesundheit — CHANGES_REQUESTED** [review]
CONTRIBUTING.md also contains a reference to `main` instead of `master`

**Comment by mcharriere** [comment]
maybe we could take the chance to migrate to `main`. wdyt?

**Comment by ubergesundheit** [comment]
Fine with me. Maybe wait for https://github.com/giantswarm/devctl/pull/538 which should make branch renaming easier?

**Comment by Gacko** [comment]
The renaming should be easy right now, did this multiple times 😌

**Comment by mleisa** [comment]
I agree it's a good opportunity to rename our default branch. @ced0ps you created a branch called `main` last month for I think upstream alignment. Don't think I can name the default main while yours exists

**Review by Gacko — APPROVED** [review]

**Review by Gacko — APPROVED** [review]

**Pull request merged**
