### PR TITLE
support behind proxy server

### PR DESCRIPTION
**Pull request by bavarianbidi**
This PR:

- adds support for running behind a proxy
- support `proxy` values
- support `cluster.proxy` values (managed/injected via `cluster-apps-operator`)
- custom `proxy` values take precedence over `cluster.proxy` variables

#### Optional app

- [ ] fresh install
- [ ] upgrade from previous version

#### Pre-installed app

- [ ] fresh install during cluster creation
- [ ] upgrade from previous version in a pre-existing cluster

#### Other testing

- [ ] check reconciliation of existing resources after upgrading

### Checklist

- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by Gacko** [comment]
From my experience of operating and supporting Squid proxies for years, I can tell that there shouldn't be a difference between uppercase and lowercase. At least I never had the case that this really made a difference. So lowercase should be fine.

Did you remove those whitespaces manually or is this from your tooling?

**Comment by bavarianbidi** [comment]
> From my experience of operating and supporting Squid proxies for years, I can tell that there shouldn't be a difference between uppercase and lowercase. At least I never had the case that this really made a difference. So lowercase should be fine.
> 
> Did you remove those whitespaces manually or is this from your tooling?

@Gacko 

as `cert-manager` is written in go, setting only `lowercase` should be fine. I just keep it consistent over multiple implementations after i've read https://about.gitlab.com/blog/2021/01/27/we-need-to-talk-no-proxy/#no_proxy.

oh, whitespaces got removed when i safe via `vscode`. If wanted i can revert these changes and safe without formating.

**Comment by Gacko** [comment]
I didn't expect someone bringing so much effort about uppercase and lowercase of proxy environment variables like the one which wrote this article. :D So yeah, your approach it totally legit, thank you!

Regarding whitespaces: I don't care. This app is not aligned to upstream, so it's fine. Decide on your own. :)

**Review by ced0ps — APPROVED** [review]
LGTM
I vote for removing whitespaces. Also the change on line 308/309 makes so much sense. Is that from tooling too?

**Comment by bavarianbidi** [comment]
> LGTM I vote for removing whitespaces. Also the change on line 308/309 makes so much sense. Is that from tooling too?

yes, all changes in `values.yaml` are formated by [this yaml formater plugin](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml).

**Review by Gacko — APPROVED** [review]

**Review by ced0ps — COMMENTED** [review]
As @Gacko is working on aligning this repo with the upstream project, is there a discussion to be had about committing these changes upstream?
LGTM

**Comment by Gacko** [comment]
I'm aligning `nginx-ingress-controller-app`, not `cert-manager-app`. ;)

**Comment by Gacko** [comment]
@bavarianbidi Need support on this?

**Comment by bavarianbidi** [comment]
> @bavarianbidi Need support on this?

hey @Gacko no, thanks ... everything fine ... just tested a bunch of other things to complete MCs+WCs behind a proxy.
I'm currently doing some last (and hopefully final tests) to get everything working. If it's ok i would keep this PR open since i'm really sure i didn't break anything :sweat_smile:

**Pull request merged**
